# Generated by Django 5.1.3 on 2024-11-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='complete_state',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='complete_state',
            new_name='is_completed',
        ),
    ]
